import { StyleSheet } from "react-native";

export default StyleSheet.create({
    text: { fontSize: 16, marginBottom: 10 },
    recipeRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 5 },
    recipe: { fontSize: 18, backgroundColor: "#cececeff", padding: 10, borderRadius: 10 },
    one_row: { display: "flex", flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
    modal: { backgroundColor: "#ffffffff", padding: 24 },
    closeButton: { padding: 12 },
    modal_container: { width: '100%', height: "100%", backgroundColor: '#ffffffff', padding: 24 },
    addIngredientButton: { margin: 3 },
    addGroceryButton: { margin: 3 },
    openRecipeModuleButton: { padding: 12, backgroundColor: "#ffffffff", alignItems: "center", borderRadius: 24 },
    addRecipeButtonDisabled: { padding: 12, backgroundColor: "#E0E0E0", alignItems: "center", marginTop: 5 },
    addRecipeButtonEnabled: { padding: 12, backgroundColor: "#2289ffff", alignItems: "center", marginTop: 5 },
    container: { flex: 1, padding: 20, backgroundColor: "#f4f6f7" },
    header: { fontSize: 24, fontWeight: "bold", marginBottom: 20 },
    inputRow: { flexDirection: "row", marginBottom: 20 },
    input: { flex: 1, borderWidth: 1, borderColor: "#ccc", borderRadius: 8, padding: 10, marginRight: 10 },
    groceryRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 5 },
    ingredientRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 5 },
    grocery: { fontSize: 18 },
    ingredient: { fontSize: 18 },
    scrollView: { paddingRight: 10 },
    select: { width: 75, marginRight: 10 },
    title: { fontSize: 20, fontWeight: "bold", marginTop: 20, marginBottom: 10 },
    suggestions: { backgroundColor: "#f5f5f5", borderRadius: 8, padding: 10, marginBottom: 10, },
    suggestion: { paddingVertical: 8, fontSize: 16, borderBottomWidth: 1, borderBottomColor: "#ddd", },

    toast: {
        position: "absolute",
        top: 50,
        left: 20,
        right: 20,
        backgroundColor: "#2e7d32",
        padding: 12,
        borderRadius: 10,
        zIndex: 1000,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },

    toastText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
    },
});
